### PR TITLE
docs: clarify USBs are vertical, through hole mount

### PR DESCRIPTION
**Pull request by amoshydra**
> Feel free to make any edit to the PR as required

## Summary

Provide additional clarification for the type of USB compatible with the PCB with example.
- 1x Micro USB Receptacle, Type B, Through Hole, Vertical, ~~With Through Hole Shell Stakes~~ ~~([example](https://www.mouser.com/ProductDetail/GCT/USB3145-30-1-A?qs=KUoIvG/9IlYD1lvSRu5iyg==))~~ ([example](https://www.mouser.com/ProductDetail/GCT/USB3131-30-0230-A?qs=KUoIvG/9IlYmRfH6E2AKbw==))
- 1x USB Connectors USB 2.0, Type A, Receptacle, Vertical, 4 Pins ([example](https://www.mouser.com/ProductDetail/Amphenol-Commercial-Products/GSB11111ALF?qs=%2BRAvXJslkuBFR1fwnWS5IA==))

The example provided has dataset and 3D view of the component to provide better reference for the parts.

## Motivation

Some of the shops / online store often sell horizontal mount type ([example from aliexpress when searched for "usb a connector"](https://www.aliexpress.com/item/32769985312.html)). These are not immediately compatible with the PCB.

This is what I've incorrectly purchased earlier :) 

261813136-39c10988-c39e-44f8-ac2d-ae7be2d4827e

### CODE REVIEW

**Comment by Hypfer** [comment]
Did you order and test those examples? The micro USB one doesn't look correct with its plastic feet

**Comment by amoshydra** [comment]
> Did you order and test those examples? The micro USB one doesn't look correct with its plastic feet

No, I haven't ordered, but planning to purchase one from aliexpress.

You are right about the plastic feet. Didn't notice that earlier.
Would this be a more accurate example? https://www.mouser.com/ProductDetail/GCT/USB3131-30-0230-A?qs=KUoIvG/9IlYmRfH6E2AKbw==

**Comment by amoshydra** [comment]
Updated the commit with this instead:

> 1x Micro USB Receptacle, Type B, Through-Hole, Vertical ([example](https://www.mouser.com/ProductDetail/GCT/USB3131-30-0230-A?qs=KUoIvG/9IlYmRfH6E2AKbw==))

**Comment by Hypfer** [comment]
As I bought generic parts from aliexpress, I do not want to recommend any other parts that haven't been tested.

Instead, I've tried to solve the issue you've faced with this commit:
https://github.com/Hypfer/valetudo-dreameadapter/commit/9290f54e0a99e00f84b480a486cba4f4bfc5148a

**Comment by amoshydra** [comment]
> I do not want to recommend any other parts that haven't been tested.

understood.

Anyway, I manage to find the keyword that lead to the correct part. They seems to call these vertical mount as "vertical seat" / " vertical mother seat"

**Pull request closed without merging**
